<apex:page >
    <h1>Hello, World!</h1>

    <section>
        <ol>
            <li><apex:outputLink value="https://www.google.com">Google</apex:outputLink></li>
            <li><apex:outputLink value="https://www.youtube.com">Youtube</apex:outputLink></li>
            <li><apex:outputLink value="https://www.facebook.com">Facebook</apex:outputLink></li>
            <li><apex:outputLink value="https://www.twitter.com">Twitter</apex:outputLink></li>
        </ol>
    </section>
</apex:page>
